name: Dev - ECR Login Windows 2022

on:
  push:

jobs:
  ecrLogin:
    name: Login to ECR
    runs-on: windows-2022
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.21.5

    - uses: actions/checkout@v4

    - run: |
        $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv
        choco install make && choco install zip && make amazon-ecr-credential-helper
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}