name: Dev - ECR Login Linux

on:
  push:

jobs:
  ecrLogin:
    name: Login to ECR
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.21.5

    - uses: actions/checkout@v4

    - run: make ecr-public-login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}